import Head from "next/head";
import Link from "next/link";
import { useRef } from "react";

const Home = () => {
  const usernameRef = useRef<HTMLInputElement>(null)
  const login = () => {
    if (usernameRef.current?.value === '') {
      alert('Please enter a username')
      return;
    };

    window.location.href = '/chat'
  }
  return (
    <main className="max-w-2xl mx-auto h-screen py-16 relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-amber-300 p-4 rounded-t-xl w-full flex justify-between items-center">
        <h1 className="text-4xl font-bold cursor-pointer">Chatt</h1>
        <div className="flex justify-between gap-x-4 items-center"></div>
      </section>
      <section className="text-neutral-700 flex justify-between items-center bg-white font-semibold p-4 rounded-b">
        <div>
          <label className="block">Username</label>
          <input
            ref={usernameRef}
            type="text"
            placeholder="Username"
            className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-amber-600"
          />
        </div>
        <button onClick={login} className="px-4 py-2 mt-8 rounded transition duration-300 bg-amber-300 hover:bg-neutral-700/30 hover:text-white active:bg-amber-300">Login</button>
      </section>
    </main>
  );
};

export default Home;
